"""
Author: L. Saetta
Date last modified: 2026-09-22
License: MIT
Description: Expose hello_world through FastAPI with health and readiness probes.
"""

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Annotated

from fastapi import FastAPI, HTTPException, Request
from langgraph.graph.state import CompiledStateGraph
from pydantic import BaseModel, StringConstraints

from demos.hello_world.agent import build_agent


class GreetingRequest(BaseModel):
    """Validated name with surrounding whitespace removed."""

    name: Annotated[
        str, StringConstraints(strict=True, strip_whitespace=True, min_length=1)
    ]


class GreetingResponse(BaseModel):
    """Greeting generated by the agent."""

    message: str


@asynccontextmanager
async def lifespan(application: FastAPI) -> AsyncIterator[None]:
    """Initialize the graph at startup and clear it at shutdown.

    Args:
        application: The service instance that owns the graph.

    Yields:
        Control to the running HTTP service after graph compilation.
    """
    application.state.agent = build_agent()
    try:
        yield
    finally:
        application.state.agent = None


app = FastAPI(title="hello_world", lifespan=lifespan)


def get_agent(request: Request) -> CompiledStateGraph:
    """Retrieve the initialized graph.

    Args:
        request: Incoming request containing the application state.

    Returns:
        The initialized graph.

    Raises:
        HTTPException: If startup has not completed or shutdown has begun.
    """
    agent = getattr(request.app.state, "agent", None)
    if agent is None:
        raise HTTPException(status_code=503, detail="Agent is not ready")
    return agent


@app.post("/hello", response_model=GreetingResponse)
async def hello(payload: GreetingRequest, request: Request) -> GreetingResponse:
    """Execute the greeting graph for a single request.

    Args:
        payload: Validated input name.
        request: Incoming request containing the application state.

    Returns:
        The greeting produced by LangGraph.

    Raises:
        HTTPException: If the graph is not ready.
    """
    result = await get_agent(request).ainvoke({"name": payload.name})
    return GreetingResponse(message=result["message"])


@app.get("/health")
async def health() -> dict[str, str]:
    """Return the HTTP service liveness status.

    Returns:
        A status indicating the HTTP service is responsive.
    """
    return {"status": "ok"}


@app.get("/ready")
async def ready(request: Request) -> dict[str, str]:
    """Check whether the greeting graph is initialized.

    Args:
        request: Incoming request containing the application state.

    Returns:
        A ready status when the graph is available.

    Raises:
        HTTPException: If the graph is not ready.
    """
    get_agent(request)
    return {"status": "ready"}
